"""empty message

Revision ID: d243ce140d8d
Revises: 30fb40cb4da9
Create Date: 2021-03-04 16:32:51.320328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd243ce140d8d'
down_revision = '30fb40cb4da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('daysago', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'daysago')
    # ### end Alembic commands ###
